name: RemindMeAt
favicon: null
layout_spectrum: 0
typography_spectrum: 0.31452
title: RemindMeAt - Location based notes and reminders
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72900820-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bc6000'
    - '#161511'
    - '#e08429'
    - '#bea9a0'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
