name: RemindMeAt
favicon: null
layout_spectrum: 0.74307
typography_spectrum: 0.31452
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bc6000'
    - '#161511'
    - '#e08429'
    - '#bea9a0'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
